apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp2
  labels:
    app: myapp2
    kubernetes.azure.com/generator: devhub
  namespace: simple-feed-reader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp2
  template:
    metadata:
      labels:
        app: myapp2
    spec:
      containers:
        - name: myapp2
          image: acrfortests.azurecr.io/simple-feed-reader:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
