apiVersion: v1
kind: Service
metadata:
  name: myapp2
  namespace: simple-feed-reader
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: myapp2
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000