apiVersion: v1
kind: Service
metadata:
  name: simple-feed-reader-service
  namespace: simple-feed-reader
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: simple-feed-reader
  ports:
    - port: 80
      targetPort: 5000